package io.github.nexllm.gateway.llm.model.chat;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Builder;

@Builder
@JsonInclude(Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
public record Usage(
    @JsonProperty("completion_tokens") Integer completionTokens,
    @JsonProperty("prompt_tokens") Integer promptTokens,
    @JsonProperty("total_tokens") Integer totalTokens,
    @JsonProperty("prompt_tokens_details") PromptTokensDetails promptTokensDetails,
    @JsonProperty("completion_tokens_details") CompletionTokenDetails completionTokenDetails,
    @JsonProperty("prompt_cache_hit_tokens") Integer promptCacheHitTokens,
    @JsonProperty("prompt_cache_miss_tokens") Integer promptCacheMissTokens) {

    /**
     * Breakdown of tokens used in the prompt
     *
     * @param audioTokens Audio input tokens present in the prompt.
     * @param cachedTokens Cached tokens present in the prompt.
     */
    @JsonInclude(Include.NON_NULL)
    public record PromptTokensDetails(
        @JsonProperty("audio_tokens") Integer audioTokens,
        @JsonProperty("cached_tokens") Integer cachedTokens) {

    }

    /**
     * Breakdown of tokens used in a completion.
     *
     * @param reasoningTokens Number of tokens generated by the model for reasoning.
     * @param acceptedPredictionTokens Number of tokens generated by the model for accepted predictions.
     * @param audioTokens Number of tokens generated by the model for audio.
     * @param rejectedPredictionTokens Number of tokens generated by the model for rejected predictions.
     */
    @JsonInclude(Include.NON_NULL)
    @JsonIgnoreProperties(ignoreUnknown = true)
    public record CompletionTokenDetails(
        @JsonProperty("reasoning_tokens") Integer reasoningTokens,
        @JsonProperty("accepted_prediction_tokens") Integer acceptedPredictionTokens,
        @JsonProperty("audio_tokens") Integer audioTokens,
        @JsonProperty("rejected_prediction_tokens") Integer rejectedPredictionTokens) {

    }
}
