package io.github.nexllm.infra.kafka.constant;

/**
 * AUTO-GENERATED by infra-init/scripts/kafka_gen.py
 * Source: config/kafka.yaml
 */
public final class KafkaTopics {
    public static final String IAM_USER_EVENTS = "iam.user.events";
    public static final String IAM_API_KEY_DELETED = "iam.api-key.deleted";

    private KafkaTopics() {}
}
