import os

# Java Class Template (with dynamic package)
JAVA_TEMPLATE = """package {package};

/**
 * AUTO-GENERATED by infra-init/scripts/kafka_gen.py
 * Source: config/kafka.yaml
 */
public final class {class_name} {{
{fields}
    private {class_name}() {{}}
}}
"""

# Python Class Template
PYTHON_TEMPLATE = """# AUTO-GENERATED by infra-init/scripts/kafka_gen.py

class {class_name}:
{fields}
"""

def run_kafka_gen(config):
    """Generate constants using metadata from config.yaml."""
    print("\n--- [Module: Kafka Constant Generation] ---")

    if 'topics' not in config or 'codegen' not in config:
        print("  ⚠️ Missing topics or codegen config. Skipping.")
        return

    # 1. Prepare fields from topics
    java_fields = ""
    python_fields = ""
    for t in config['topics']:
        const_name = t['name'].replace('.', '_').replace('-', '_').upper()
        java_fields += f'    public static final String {const_name} = "{t["name"]}";\n'
        python_fields += f'    {const_name} = "{t["name"]}"\n'

    # 2. Process Java Generation
    java_meta = config['codegen']['java']
    # Convert package "com.example.foo" to "com/example/foo"
    package_path = java_meta['package'].replace('.', '/')
    # Full absolute path: output_dir + package_path + class_name.java
    java_out_dir = os.path.abspath(os.path.join(
        os.path.dirname(__file__), "..", java_meta['output_dir'], package_path
    ))
    java_file_path = os.path.join(java_out_dir, f"{java_meta['class_name']}.java")

    os.makedirs(java_out_dir, exist_ok=True)
    with open(java_file_path, "w", encoding="utf-8", newline='\n') as f:
        f.write(JAVA_TEMPLATE.format(
            package=java_meta['package'],
            class_name=java_meta['class_name'],
            fields=java_fields
        ))
    print(f"  ✅ Java: {java_meta['package']}.{java_meta['class_name']} -> {java_file_path}")

    # 3. Process Python Generation
    py_meta = config['codegen']['python']
    py_file_path = os.path.abspath(os.path.join(
        os.path.dirname(__file__), "..", py_meta['output_file']
    ))

    os.makedirs(os.path.dirname(py_file_path), exist_ok=True)
    with open(py_file_path, "w", encoding="utf-8", newline='\n') as f:
        f.write(PYTHON_TEMPLATE.format(
            class_name=py_meta['class_name'],
            fields=python_fields
        ))
    print(f"  ✅ Python: {py_meta['class_name']} -> {py_file_path}")
